config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :uploads

  resources :goods

  root to: 'uploads#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goods.rb
class Goods < ApplicationRecord
  self.table_name = 'goods'

  scope :with_suppliers, -> { joins('INNER JOIN suppliers ON suppliers.code = goods.supplier_code') }

  belongs_to :supplier, foreign_key: :supplier_code, primary_key: :code

  validates :sku, presence: true, uniqueness: true
  validates :supplier_code, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
end

app/models/upload.rb
class Upload < ApplicationRecord
  SUPPLIER_CSV_FILE = 'suppliers.csv'
  GOODS_CSV_FILE = 'sku.csv'

  has_attached_file :attachment
  validates_attachment_content_type :attachment, content_type: ['text/csv']
  validates_attachment_file_name :attachment, matches: [SUPPLIER_CSV_FILE, GOODS_CSV_FILE]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: GoodsDatatable.new(view_context) }
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def new
    @upload = Upload.new
  end

  def create
    begin
      @upload = Upload.new(upload_params)
    rescue ActionController::ParameterMissing
      flash[:error] = "Couldn't find attachment."
      return redirect_to(new_upload_url)
    end

    if @upload.save
      UploaderJob.perform_later(upload_id: @upload.id)
      return redirect_to(goods_url)
    else
      flash[:error] = "Couldn't save file."
      return redirect_to(new_upload_url)
    end
  end

  private

  def upload_params
    params.require(:upload)
          .permit(:attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/goods/index.html.erb
<%= link_to '<- back to upload', new_upload_path %>
<p><b>NOTE:</b> please periodically update page, results will be saved after few seconds.</p>
<table id="goods" class="display" data-source="<%= goods_url(format: "json") %>">
  <thead>
    <tr>
      <th>SKU</th>
      <th>Price</th>
      <th>Additional Field 1</th>
      <th>Additional Field 2</th>
      <th>Additional Field 3</th>
      <th>Additional Field 4</th>
      <th>Additional Field 5</th>
      <th>Additional Field 6</th>
      <th>Supplier Code</th>
      <th>Supplier Name</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/uploads/new.html.erb
<% if flash[:error].present? %>
  <div class="error"><%= flash[:error] %></div>
<% end %>

<p><b>NOTE:</b></p>
<ol>
  <li>Upload suppliers.csv</li>
  <li>Upload sku.csv</li>
</ol>
<%= form_for @upload, url: uploads_path do |form| %>
  <%= form.file_field :attachment %>
  <%= form.submit 'Upload' %>
<% end %>